In [28]:
import pandas as pd
import requests
url = 'https://gist.githubusercontent.com/skywalker0803r/5e9725321f403e2f6f14122165d7b3fd/raw/5108b1e7c76daa103ed8a6e34556145d4d0d28b6/Rawdataencryption.py'
exec(requests.get(url).text)
feed = Rawdataencryption('RDS2品質-20220520.xlsx','Feed')
feed

,單元,RDS2,RDS2.1,RDS2.2,RDS2.3,RDS2.4,RDS2.5,RDS2.6,RDS2.7,RDS2.8,...,RDS2.18,RDS2.19,RDS2.20,RDS2.21,RDS2.22,RDS2.23,RDS2.24,RDS2.25,RDS2.26,RDS2.27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,111.8030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,111.9578,111.95840,127.14,NaN,141.86,NaN,NaN,NaN,NaN
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,NaN,363.4,433.4,466.8,NaN,549.0,NaN,623.2,NaN,698.6,...,114.2342,111.9648,111.96534,126.08,2514.38,151.16,121.0,121.46,NaN,NaN
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
ProductDSLGO = Rawdataencryption('RDS2品質-20220520.xlsx','Product-DSLGO')
ProductDSLGO

,單元,RDS2,RDS2.1,RDS2.2,RDS2.3,RDS2.4,RDS2.5,RDS2.6,RDS2.7,RDS2.8,...,RDS2.15,RDS2.16,RDS2.17,RDS2.18,RDS2.19,RDS2.20,RDS2.21,RDS2.22,RDS2.23,RDS2.24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,611.000,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,337.5,362.4,372.9,389.2,402.2,NaN,424.7,434.4,443.7,...,162.04,NaN,NaN,111.86278,111.86324,143.4182,254.175,NaN,NaN,122.0
307,NaN,296.1,367.7,376.1,391.5,404.4,NaN,425.8,435.2,443.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,NaN,340.8,368.7,375.1,391.0,403.7,NaN,424.0,432.5,440.5,...,NaN,NaN,NaN,NaN,NaN,NaN,393.555,NaN,NaN,NaN
309,NaN,337.7,370.6,376.7,392.6,404.7,NaN,425.1,434.1,442.4,...,161.66,111.88284,303.662,111.86415,111.86461,143.1581,327.325,218.075,116.039,122.0
310,NaN,339.4,369.6,377.2,392.3,404.7,NaN,425.8,434.7,443.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
ProductDSAR = Rawdataencryption('RDS2品質-20220520.xlsx','Product-DSAR')
ProductDSAR

,單元,RDS2,RDS2.1,RDS2.2,RDS2.3,RDS2.4,RDS2.5,RDS2.6,RDS2.7,RDS2.8,...,RDS2.14,RDS2.15,RDS2.16,RDS2.17,RDS2.18,RDS2.19,RDS2.20,RDS2.21,RDS2.22,RDS2.23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,125.00,NaN,NaN,NaN,NaN,1631.00,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,111.7480,NaN,878.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,115.57,119.13,111.4153,NaN,111.9289,131.75,NaN,121.0,121.0,NaN
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,111.4890,NaN,111.9347,130.81,NaN,NaN,NaN,NaN
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,111.4804,NaN,111.9336,130.97,NaN,NaN,NaN,NaN
309,NaN,457.2,508.4,524.6,549.6,571.8,598.2,625.4,654.2,673.8,...,116.50,120.56,111.5004,116.74,111.9334,131.00,1923.85,119.0,119.0,111.92138
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,111.4920,NaN,111.9336,130.98,NaN,NaN,NaN,NaN

In [31]:
OP = Rawdataencryption('RDS2品質-20220520.xlsx','OP')
OP

,Unnamed: 0,RDS2,RDS2.1,RDS2.2,RDS2.3,RDS2.4,RDS2.5,RDS2.6,RDS2.7,RDS2.8,...,RDS2.82,RDS2.83,RDS2.84,RDS2.85,RDS2.86,RDS2.87,RDS2.88,RDS2.89,RDS2.90,RDS2.91
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,578.9728,490.0635,489.6590,489.86125,501.6363,501.8767,501.75650,496.2589,496.1692,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,NaN,582.8199,490.1206,489.7996,489.96010,501.5562,501.7037,501.62995,496.2409,496.1441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,NaN,582.0358,490.1164,489.4867,489.80155,501.3816,501.6660,501.52380,496.1439,495.9865,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,NaN,581.8906,490.1538,489.4843,489.81905,501.3670,501.6917,501.52935,496.1567,495.9991,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,NaN,582.4168,490.1169,489.5409,489.82890,501.3406,501.6246,501.48260,496.1192,495.9868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
feed.to_csv('feed.csv')
ProductDSLGO.to_csv('ProductDSLGO.csv')
ProductDSAR.to_csv('ProductDSAR.csv')
OP.to_csv('OP.csv')